/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mist_node_MistNodeApi */

#ifndef _Included_mist_node_MistNodeApi
#define _Included_mist_node_MistNodeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mist_node_MistNodeApi
 * Method:    updateBool
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_mist_node_MistNodeApi_updateBool
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     mist_node_MistNodeApi
 * Method:    updateInt
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_mist_node_MistNodeApi_updateInt
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     mist_node_MistNodeApi
 * Method:    updateString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mist_node_MistNodeApi_updateString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     mist_node_MistNodeApi
 * Method:    updateFloat
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_mist_node_MistNodeApi_updateFloat
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     mist_node_MistNodeApi
 * Method:    addEndpoint
 * Signature: (Lmist/node/Endpoint;)V
 */
JNIEXPORT void JNICALL Java_mist_node_MistNodeApi_addEndpoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     mist_node_MistNodeApi
 * Method:    startMistApp
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mist_node_MistNodeApi_startMistApp
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class mist_node_MistNodeApi_MistNodeApiHolder */

#ifndef _Included_mist_node_MistNodeApi_MistNodeApiHolder
#define _Included_mist_node_MistNodeApi_MistNodeApiHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
