/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_ct_mist_mistnodeapi_WishBridgeJni */

#ifndef _Included_fi_ct_mist_mistnodeapi_WishBridgeJni
#define _Included_fi_ct_mist_mistnodeapi_WishBridgeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_ct_mist_mistnodeapi_WishBridgeJni
 * Method:    register
 * Signature: (Lfi/ct/mist/mistnodeapi/WishBridge;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_fi_ct_mist_mistnodeapi_WishBridgeJni_register
  (JNIEnv *, jobject, jobject);

/*
 * Class:     fi_ct_mist_mistnodeapi_WishBridgeJni
 * Method:    receive_core_to_app
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_mistnodeapi_WishBridgeJni_receive_1core_1to_1app
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     fi_ct_mist_mistnodeapi_WishBridgeJni
 * Method:    connected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_mistnodeapi_WishBridgeJni_connected
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
