/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_ct_mist_referencelibrary_api_node_NodeApiJni */

#ifndef _Included_fi_ct_mist_referencelibrary_api_node_NodeApiJni
#define _Included_fi_ct_mist_referencelibrary_api_node_NodeApiJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_ct_mist_referencelibrary_api_node_NodeApiJni
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_referencelibrary_api_node_NodeApiJni_register
  (JNIEnv *, jobject);

/*
 * Class:     fi_ct_mist_referencelibrary_api_node_NodeApiJni
 * Method:    result
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_referencelibrary_api_node_NodeApiJni_result
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
