/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_ct_mist_api_mist_MistApiJni */

#ifndef _Included_fi_ct_mist_api_mist_MistApiJni
#define _Included_fi_ct_mist_api_mist_MistApiJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_ct_mist_api_mist_MistApiJni
 * Method:    start_mist_app
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_api_mist_MistApiJni_start_1mist_1app
  (JNIEnv *, jobject, jstring);

/*
 * Class:     fi_ct_mist_api_mist_MistApiJni
 * Method:    destroy_mist_app
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_api_mist_MistApiJni_destroy_1mist_1app
  (JNIEnv *, jobject);

/*
 * Class:     fi_ct_mist_api_mist_MistApiJni
 * Method:    receive_mist_api
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_api_mist_MistApiJni_receive_1mist_1api
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class fi_ct_mist_api_mist_MistApiJni_CallbackList */

#ifndef _Included_fi_ct_mist_api_mist_MistApiJni_CallbackList
#define _Included_fi_ct_mist_api_mist_MistApiJni_CallbackList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
