/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_ct_mist_referencelibrary_bridge_WishBridgeJni */

#ifndef _Included_fi_ct_mist_referencelibrary_bridge_WishBridgeJni
#define _Included_fi_ct_mist_referencelibrary_bridge_WishBridgeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_ct_mist_referencelibrary_bridge_WishBridgeJni
 * Method:    register
 * Signature: (Lfi/ct/mist/referencelibrary/bridge/WishBridge;)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_referencelibrary_bridge_WishBridgeJni_register
  (JNIEnv *, jobject, jobject);

/*
 * Class:     fi_ct_mist_referencelibrary_bridge_WishBridgeJni
 * Method:    receive_core_to_app
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_referencelibrary_bridge_WishBridgeJni_receive_1core_1to_1app
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
