/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi */

#ifndef _Included_fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi
#define _Included_fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi
 * Method:    updateBool
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi_updateBool
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi
 * Method:    updateInt
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi_updateInt
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi
 * Method:    updateString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi_updateString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi
 * Method:    updateFloat
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi_updateFloat
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi
 * Method:    addEndpoint
 * Signature: (Lfi/ct/mist/referencelibrary/api/mistNode/Endpoint;)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi_addEndpoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi
 * Method:    startMistApp
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi_startMistApp
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi_MistNodeApiHolder */

#ifndef _Included_fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi_MistNodeApiHolder
#define _Included_fi_ct_mist_referencelibrary_api_mistNode_MistNodeApi_MistNodeApiHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
